spectacles = ["shenglongjia", "huangshan", "guiling", "wuyueshan", "talimuhu"]
print(len(spectacles))
print(spectacles)
print(sorted(spectacles))
print(spectacles)
print(sorted(spectacles, reverse=True))
print(spectacles)
spectacles.reverse()
print(spectacles)
spectacles.reverse()
print(spectacles)
spectacles.sort()
print(spectacles)
spectacles.sort(reverse=True)
print(spectacles)
